/* https://github.com/huguesjohnson/DubbelLib/blob/main/LICENSE */

package com.huguesjohnson.dubbel.opml;

import java.util.ArrayList;
import java.util.List;

public class OPMLObject{
	private String version;
	private OPMLHead head;
	private List<OPMLOutline> body;

	public OPMLObject(){
		this.head=new OPMLHead();
		this.body=new ArrayList<OPMLOutline>();
	}
	
	/* autogenerated code below */

	public OPMLObject(OPMLHead head, List<OPMLOutline> body) {
		super();
		this.head = head;
		this.body = body;
	}


	public OPMLHead getHead() {
		return head;
	}


	public void setHead(OPMLHead head) {
		this.head = head;
	}


	public List<OPMLOutline> getBody() {
		return body;
	}


	public void setBody(List<OPMLOutline> body) {
		this.body = body;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}
}