/* https://github.com/huguesjohnson/DubbelLib/blob/main/LICENSE */

package com.huguesjohnson.dubbel.webpublisher;

public class ReplacementBlock{
	private String startTag;
	private String endTag;
	private String replacementTextPath;
	private String replacementText;

	public ReplacementBlock(){}

	/* autogenerated code */	

	public String getStartTag() {
		return startTag;
	}

	public void setStartTag(String startTag) {
		this.startTag = startTag;
	}

	public String getEndTag() {
		return endTag;
	}

	public void setEndTag(String endTag) {
		this.endTag = endTag;
	}

	public String getReplacementText() {
		return replacementText;
	}

	public void setReplacementText(String replacementText) {
		this.replacementText = replacementText;
	}

	public String getReplacementTextPath() {
		return replacementTextPath;
	}

	public void setReplacementTextPath(String replacementTextPath) {
		this.replacementTextPath = replacementTextPath;
	}
}