/* https://github.com/huguesjohnson/DubbelLib/blob/main/LICENSE */

package com.huguesjohnson.dubbel.webpublisher;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

public class ReplacementBlockList extends ArrayList<ReplacementBlock>{
	//just here to deal with compiler warnings
	private static final long serialVersionUID=666L;

	public ReplacementBlock findByStartTag(String startTag){
		String search=startTag.trim();
		Iterator<ReplacementBlock> i=this.iterator();
		while(i.hasNext()){
			ReplacementBlock r=i.next();
			if(r.getStartTag().equalsIgnoreCase(search)){
				return(r);
			}
		}
		return(null);//yeah, that's right
	}
	
	/* autogenerated code */	
	
	public ReplacementBlockList() {
		super();
	}

	public ReplacementBlockList(Collection<? extends ReplacementBlock> c) {
		super(c);
	}

	public ReplacementBlockList(int initialCapacity) {
		super(initialCapacity);
	}
}