/* https://github.com/huguesjohnson/DubbelLib/blob/main/LICENSE */

package com.huguesjohnson.dubbel.webpublisher;

import java.io.Serializable;
import java.util.Map;

public class Settings implements Serializable{
	private static final long serialVersionUID=648913666L;

	private boolean dryRun=false;
	private boolean rebuildSitemap=true;
	private boolean rebuildRssLinks=true;  
	private boolean rebuildPagesFromCsv=true; 
	private String templateDirectory;
	private String stagingDirectory;
	private String publishDirectory;
	private Map<String,String> rssPages;
	private Map<String,String> csvPages;
	
	/* autogenerated code */	
	
	public boolean isDryRun() {
		return dryRun;
	}
	public void setDryRun(boolean dryRun) {
		this.dryRun = dryRun;
	}
	public boolean isRebuildSitemap() {
		return rebuildSitemap;
	}
	public void setRebuildSitemap(boolean rebuildSitemap) {
		this.rebuildSitemap = rebuildSitemap;
	}
	public boolean isRebuildRssLinks() {
		return rebuildRssLinks;
	}
	public void setRebuildRssLinks(boolean rebuildRssLinks) {
		this.rebuildRssLinks = rebuildRssLinks;
	}
	public boolean isRebuildPagesFromCsv() {
		return rebuildPagesFromCsv;
	}
	public void setRebuildPagesFromCsv(boolean rebuildPagesFromCsv) {
		this.rebuildPagesFromCsv = rebuildPagesFromCsv;
	}
	public String getTemplateDirectory() {
		return templateDirectory;
	}
	public void setTemplateDirectory(String templateDirectory) {
		this.templateDirectory = templateDirectory;
	}
	public String getStagingDirectory() {
		return stagingDirectory;
	}
	public void setStagingDirectory(String stagingDirectory) {
		this.stagingDirectory = stagingDirectory;
	}
	public String getPublishDirectory() {
		return publishDirectory;
	}
	public void setPublishDirectory(String publishDirectory) {
		this.publishDirectory = publishDirectory;
	}
	public Map<String, String> getRssPages() {
		return rssPages;
	}
	public void setRssPages(Map<String, String> rssPages) {
		this.rssPages = rssPages;
	}
	public Map<String, String> getCsvPages() {
		return csvPages;
	}
	public void setCsvPages(Map<String, String> csvPages) {
		this.csvPages = csvPages;
	}
}