/* https://github.com/huguesjohnson/DubbelLib/blob/main/LICENSE */

package com.huguesjohnson.dubbel.webpublisher;

import java.util.Map;

public class Settings{
	private boolean dryRun=false;
	private boolean rebuildSitemap=true;
	private boolean rebuildRssLinks=true;  
	private boolean rebuildPagesFromCsv=true; 
	private String templateDirectory;
	private String stagingDirectory;
	private String publishDirectory;
	private Map<String,String> opmlPages;
	private Map<String,String> csvPages;
	private Map<String,String> staticTemplates;
	private ReplacementList replacements;
	
	/* autogenerated code */	
	
	public boolean isDryRun() {
		return dryRun;
	}
	public void setDryRun(boolean dryRun) {
		this.dryRun = dryRun;
	}
	public boolean isRebuildSitemap() {
		return rebuildSitemap;
	}
	public void setRebuildSitemap(boolean rebuildSitemap) {
		this.rebuildSitemap = rebuildSitemap;
	}
	public boolean isRebuildRssLinks() {
		return rebuildRssLinks;
	}
	public void setRebuildRssLinks(boolean rebuildRssLinks) {
		this.rebuildRssLinks = rebuildRssLinks;
	}
	public boolean isRebuildPagesFromCsv() {
		return rebuildPagesFromCsv;
	}
	public void setRebuildPagesFromCsv(boolean rebuildPagesFromCsv) {
		this.rebuildPagesFromCsv = rebuildPagesFromCsv;
	}
	public String getTemplateDirectory() {
		return templateDirectory;
	}
	public void setTemplateDirectory(String templateDirectory) {
		this.templateDirectory = templateDirectory;
	}
	public String getStagingDirectory() {
		return stagingDirectory;
	}
	public void setStagingDirectory(String stagingDirectory) {
		this.stagingDirectory = stagingDirectory;
	}
	public String getPublishDirectory() {
		return publishDirectory;
	}
	public void setPublishDirectory(String publishDirectory) {
		this.publishDirectory = publishDirectory;
	}
	public Map<String, String> getRssPages() {
		return opmlPages;
	}
	public void setRssPages(Map<String, String> rssPages) {
		this.opmlPages = rssPages;
	}
	public Map<String, String> getCsvPages() {
		return csvPages;
	}
	public void setCsvPages(Map<String, String> csvPages) {
		this.csvPages = csvPages;
	}
	public ReplacementList getReplacements() {
		return replacements;
	}
	public void setReplacements(ReplacementList replacements) {
		this.replacements = replacements;
	}
}